use customer_shopping_behaviour;
select* from customer_data;

-- BUSINESS PROBLEMS 

-- 1.What is the total revenue generated by male versus female customers?
select gender, sum(purchase_amount) as revenue 
from customer_data
group by gender;

-- 2.Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount 
from customer_data 
where discount_applied = 'yes' and purchase_amount >= (select avg (purchase_amount)from customer_data);

-- 3.Which are the top five products with the highest average review rating?
select item_purchased , AVG(review_rating) as "Average Product Rating"
from customer_data 
group by item_purchased 
order by avg(review_rating) desc 
limit 5;

-- 4. compare the average purchase amount between standard and express shipping?
select shipping_type , 
Round(AVG (purchase_amount),2) as AVERAGE 
from customer_data 
where shipping_type in ('Standard', 'Express' )
group by shipping_type ;
-- 5.Do subscribed customers spend more? compare to non-subscribers in terms of average spend and total revenue?
SELECT subscription_status, COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount), 2) AS average_spend,
SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- 6.Which five products have the highest percentage of purchases with discounts applied? 
SELECT item_purchased,
ROUND(100 * AVG(discount_applied = 'Yes'),2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;



-- 7.How can customers be segmented into new, returning, and loyal based on their total number of previous purchases?
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases <= 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_data
GROUP BY customer_segment;


-- 8.What are the top three most purchased products within each category?
WITH item_counts AS (
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_data
GROUP BY category, item_purchased
)
SELECT * FROM item_counts WHERE item_rank <= 3;

-- 9.Are repeat buyers (more than five previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10.What is the total revenue generated by each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;